name: ae
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  google_mlkit_face_detection: ^0.11.0
  http: ^0.13.6
  provider: ^6.1.0
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  image: ^4.0.17
  permission_handler: ^11.0.1
  google_ml_kit: ^0.18.0
  intl: ^0.20.2
  image_picker: ^0.8.4+4
  supabase_flutter: ^2.0.0
  google_fonts: ^4.0.4
  url_launcher: ^6.0.20
  flutter_screenutil: ^5.9.3
  carousel_slider: ^5.0.0
  google_nav_bar: ^5.0.7
  fl_chart: ^0.70.2
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/Icon2.png"
  image_path: null
  
  remove_alpha_ios: true
